/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as UserProfileRouteImport } from './user-profile'
import { Route as TracksRouteImport } from './tracks'
import { Route as MyPlaylistsRouteImport } from './my-playlists'
import { Route as IndexRouteImport } from './index'
import { Route as TrackDetailTrackIdRouteImport } from './track-detail.$trackId'
import { Route as PlaylistDetailPlaylistIdRouteImport } from './playlist-detail.$playlistId'
import { Route as OauthCallbackRouteImport } from './oauth/callback'

const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlaylistsRoute = MyPlaylistsRouteImport.update({
  id: '/my-playlists',
  path: '/my-playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDetailTrackIdRoute = TrackDetailTrackIdRouteImport.update({
  id: '/track-detail/$trackId',
  path: '/track-detail/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistDetailPlaylistIdRoute =
  PlaylistDetailPlaylistIdRouteImport.update({
    id: '/playlist-detail/$playlistId',
    path: '/playlist-detail/$playlistId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-playlists': typeof MyPlaylistsRoute
  '/tracks': typeof TracksRoute
  '/user-profile': typeof UserProfileRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlist-detail/$playlistId': typeof PlaylistDetailPlaylistIdRoute
  '/track-detail/$trackId': typeof TrackDetailTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-playlists': typeof MyPlaylistsRoute
  '/tracks': typeof TracksRoute
  '/user-profile': typeof UserProfileRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlist-detail/$playlistId': typeof PlaylistDetailPlaylistIdRoute
  '/track-detail/$trackId': typeof TrackDetailTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-playlists': typeof MyPlaylistsRoute
  '/tracks': typeof TracksRoute
  '/user-profile': typeof UserProfileRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlist-detail/$playlistId': typeof PlaylistDetailPlaylistIdRoute
  '/track-detail/$trackId': typeof TrackDetailTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-playlists'
    | '/tracks'
    | '/user-profile'
    | '/oauth/callback'
    | '/playlist-detail/$playlistId'
    | '/track-detail/$trackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-playlists'
    | '/tracks'
    | '/user-profile'
    | '/oauth/callback'
    | '/playlist-detail/$playlistId'
    | '/track-detail/$trackId'
  id:
    | '__root__'
    | '/'
    | '/my-playlists'
    | '/tracks'
    | '/user-profile'
    | '/oauth/callback'
    | '/playlist-detail/$playlistId'
    | '/track-detail/$trackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyPlaylistsRoute: typeof MyPlaylistsRoute
  TracksRoute: typeof TracksRoute
  UserProfileRoute: typeof UserProfileRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PlaylistDetailPlaylistIdRoute: typeof PlaylistDetailPlaylistIdRoute
  TrackDetailTrackIdRoute: typeof TrackDetailTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-profile': {
      id: '/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-playlists': {
      id: '/my-playlists'
      path: '/my-playlists'
      fullPath: '/my-playlists'
      preLoaderRoute: typeof MyPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-detail/$trackId': {
      id: '/track-detail/$trackId'
      path: '/track-detail/$trackId'
      fullPath: '/track-detail/$trackId'
      preLoaderRoute: typeof TrackDetailTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist-detail/$playlistId': {
      id: '/playlist-detail/$playlistId'
      path: '/playlist-detail/$playlistId'
      fullPath: '/playlist-detail/$playlistId'
      preLoaderRoute: typeof PlaylistDetailPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyPlaylistsRoute: MyPlaylistsRoute,
  TracksRoute: TracksRoute,
  UserProfileRoute: UserProfileRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PlaylistDetailPlaylistIdRoute: PlaylistDetailPlaylistIdRoute,
  TrackDetailTrackIdRoute: TrackDetailTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
