import createClient, {type Middleware} from "openapi-fetch";
import type {paths} from "./schema"; // generated by openapi-typescript

let refreshPromise: Promise<void> | null = null;

const baseUrl = "https://musicfun.it-incubator.app/api/1.0/"

function makeRefreshToken() {
    if (!refreshPromise) {
        refreshPromise = (async (): Promise<void> => {
            const refreshToken = localStorage.getItem("musicfun-refresh-token");
            if (!refreshToken) throw new Error("No refresh token");

           const response = await fetch(baseUrl + "/auth/refresh", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    refreshToken: refreshToken
                })
            })

            if (!response.ok) {
                throw new Error("Refresh token failed.");
            }


        })()

        refreshPromise.finally(() => {
            refreshPromise = null
        })
    }
}

const authMyMiddleware: Middleware = {
    async onRequest({request}) {
        // set "foo" header
        const accessToken = localStorage.getItem('musicfun-access-token')
        if (accessToken) {
            request.headers.set("Authorization", "Bearer " + accessToken)
        }
        request.headers.set("foo", "bar");
        return request;
    },

    onResponse({response}) {
        if (!response.ok) {
            // Will produce error messages like "https://example.org/api/v1/example: 404 Not Found".
            throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
        }
    }
};

export const client = createClient<paths>({
    baseUrl: baseUrl,
    headers: {
        'api-key': "7375c246-b206-4c43-a2ae-0010f7388790"
    }
});

client.use(authMyMiddleware);
