import createClient from "openapi-fetch";
import type {paths} from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
    headers: {
        'api-key': "7375c246-b206-4c43-a2ae-0010f7388790"
    }
});
